const screens={case:'screen-case',diagnosis:'screen-diagnosis',theory:'screen-theory',apply:'screen-apply',open:'screen-open',survey:'screen-survey',result:'screen-result'};
const state={diagnosisScore:0,theoryScore:0,applyScore:0,openScore:0,openBreakdown:{},survey:{}};

const diagnosisOptions=[
{id:'social',title:'Dificultades en habilidades sociales',text:'El alumnado presenta problemas de comunicación, cooperación y relación.',good:true},
{id:'team',title:'Problemas de trabajo en equipo',text:'La colaboración entre iguales aparece como una necesidad explícita.',good:true},
{id:'adapt',title:'Baja adaptabilidad ante nuevos desafíos',text:'Existe resistencia ante situaciones nuevas y demandas cambiantes.',good:true},
{id:'curiosity',title:'Descenso de curiosidad y exploración',text:'Al final de Primaria disminuye el interés por descubrir nuevos temas.',good:true},
{id:'lifelong',title:'Resistencia hacia el aprendizaje',text:'El caso exige fomentar una disposición positiva hacia seguir aprendiendo.',good:true},
{id:'achievement',title:'Bajo rendimiento académico generalizado',text:'El centro presenta resultados académicos claramente insuficientes.',good:false},
{id:'discipline',title:'Problema principal de disciplina',text:'La prioridad es aumentar sanciones y control conductual.',good:false},
{id:'technology',title:'Falta de dispositivos como causa central',text:'El problema se explica fundamentalmente por no disponer de suficiente tecnología.',good:false}
];

const theoryItems=[
{prompt:'Un alumno mejora una conducta social al observar cómo el docente y sus compañeros modelan formas adecuadas de cooperación.',correct:'bandura',options:[['bandura','Bandura: aprendizaje social mediante observación e imitación.'],['piaget','Piaget: adaptación de tareas al desarrollo cognitivo.'],['bowlby','Bowlby: seguridad vinculada a relaciones estables.'],['erikson','Erikson: conflictos psicosociales por etapas.']]},
{prompt:'El docente ofrece apoyo temporal y ajustado para que el estudiante pueda realizar una tarea que aún no resolvería solo.',correct:'vygotsky',options:[['vygotsky','Vygotsky: zona de desarrollo próximo y andamiaje.'],['bandura','Bandura: imitación de modelos.'],['erikson','Erikson: industria frente a inferioridad.'],['piaget','Piaget: aprendizaje exclusivamente individual.']]},
{prompt:'Se diseñan tareas alcanzables que permiten al alumnado experimentar competencia, esfuerzo y progreso durante Primaria.',correct:'erikson',options:[['erikson','Erikson: industria frente a inferioridad y construcción de competencia.'],['bowlby','Bowlby: teoría del apego.'],['bandura','Bandura: aprendizaje observacional.'],['piaget','Piaget: juego simbólico preoperacional.']]},
{prompt:'El aula se plantea como un entorno seguro, estable y de apoyo que favorece la confianza para explorar y aprender.',correct:'bowlby',options:[['bowlby','Bowlby: relaciones seguras y confiables favorecen el desarrollo.'],['vygotsky','Vygotsky: zona de desarrollo próximo.'],['erikson','Erikson: identidad frente a confusión de roles.'],['bandura','Bandura: refuerzo vicario.']]},
{prompt:'Las actividades se ajustan al nivel de desarrollo cognitivo y favorecen exploración y experimentación activa.',correct:'piaget',options:[['piaget','Piaget: adecuación de actividades al desarrollo cognitivo.'],['bandura','Bandura: observación e imitación.'],['bowlby','Bowlby: apego.'],['vygotsky','Vygotsky: interacción social como único criterio.']]}
];

const applyItems=[
{prompt:'Para recuperar la curiosidad al final de Primaria...',correct:'explore',options:[['explore','Plantear proyectos, retos y experiencias de exploración donde el alumnado formule preguntas, investigue y tome decisiones.'],['repeat','Aumentar ejercicios repetitivos para reforzar obediencia y rapidez.'],['avoid','Evitar tareas abiertas para reducir incertidumbre.'],['lecture','Sustituir la exploración por explicaciones magistrales más largas.']],why:'El Tema 1 entiende el aprendizaje como un proceso continuo y promueve enseñar a aprender, buscar información, adaptarse y actuar con autonomía.'},
{prompt:'Para fortalecer habilidades sociales y trabajo en equipo...',correct:'social',options:[['social','Usar aprendizaje cooperativo, juegos de rol y resolución dialogada de conflictos, con modelado docente y retroalimentación.'],['alone','Priorizar tareas individuales para evitar desacuerdos.'],['rank','Publicar rankings de rendimiento para aumentar competitividad.'],['punish','Aplicar sanciones automáticas ante cualquier conflicto.']],why:'Bandura permite trabajar el modelado de conductas y Vygotsky destaca la interacción social como motor del aprendizaje.'},
{prompt:'Para alumnado en la etapa de industria frente a inferioridad...',correct:'competence',options:[['competence','Ofrecer tareas progresivamente desafiantes, responsabilidades reales y reconocimiento del esfuerzo y progreso.'],['easy','Evitar cualquier reto para impedir el fracaso.'],['compare','Comparar públicamente a quienes rinden mejor y peor.'],['final','Valorar solo el resultado final y no el proceso.']],why:'En Erikson, las experiencias de competencia durante esta etapa ayudan a construir una percepción positiva de capacidad; el fracaso reiterado o la comparación pueden reforzar inferioridad.'},
{prompt:'Para promover una mentalidad de aprendizaje a lo largo de la vida...',correct:'growth',options:[['growth','Tratar errores y desafíos como información para mejorar, fomentar persistencia, reflexión y aprendizaje autónomo.'],['fixed','Transmitir que las capacidades son estables y que conviene evitar aquello para lo que no se tiene facilidad.'],['reward','Depender solo de premios externos para aprender.'],['finish','Centrar la enseñanza únicamente en aprobar la etapa escolar.']],why:'El Tema 1 define el aprendizaje a lo largo de la vida como continuo, autónomo y necesario para adaptarse a contextos cambiantes.'},
{prompt:'Para implicar familia y comunidad...',correct:'community',options:[['community','Invitarlas a participar en proyectos, experiencias y actividades conectadas con contextos reales de aprendizaje.'],['exclude','Mantener el aprendizaje aislado del entorno para evitar interferencias.'],['report','Contactar con las familias únicamente cuando aparezcan problemas.'],['delegate','Delegar en las familias la responsabilidad principal del aprendizaje escolar.']],why:'El aprendizaje permanente no se limita al aula: también se produce en interacciones sociales, experiencias de vida y contextos no formales.'}
];

const commonSurvey=window.COMMON_SURVEY;
const surveyStatements=commonSurvey.statements;

function show(name){Object.values(screens).forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById(screens[name]).classList.add('active');const steps={case:1,diagnosis:2,theory:3,apply:4,open:5,survey:6,result:6};const step=steps[name];document.getElementById('progressLabel').textContent=name==='result'?'Actividad completada':`Paso ${step} de 6`;document.getElementById('progressBar').style.width=`${name==='result'?100:(step/6)*100}%`;window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.next)));
document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));
function feedback(el,html,type='good'){el.className=`feedback ${type}`;el.innerHTML=html;}

function renderDiagnosis(){const grid=document.getElementById('diagnosisGrid');diagnosisOptions.forEach(o=>{const btn=document.createElement('button');btn.className='block-option';btn.dataset.id=o.id;btn.innerHTML=`<strong>${o.title}</strong><span>${o.text}</span>`;btn.addEventListener('click',()=>btn.classList.toggle('selected'));grid.appendChild(btn);});}
function renderTheory(){const grid=document.getElementById('theoryGrid');theoryItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="theory-${i}"><option value="">Selecciona la teoría</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderApply(){const grid=document.getElementById('applyGrid');applyItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="apply-${i}"><option value="">Selecciona la actuación más adecuada</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderSurvey(){const box=document.getElementById('surveyItems');surveyStatements.forEach((s,i)=>{const div=document.createElement('div');div.className='survey-item';div.innerHTML=`<p><strong>${i+1}.</strong> ${s}</p><div class="likert">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="survey-${i}" value="${n}"> ${n}</label>`).join('')}</div>`;box.appendChild(div);});document.getElementById('surveyUseful').innerHTML='<option value="">Selecciona una opción</option>'+commonSurvey.usefulOptions.map(o=>`<option>${o}</option>`).join('');}

renderDiagnosis();renderTheory();renderApply();renderSurvey();

document.getElementById('evaluateDiagnosis').addEventListener('click',()=>{const chosen=[...document.querySelectorAll('.block-option.selected')].map(x=>x.dataset.id);const good=diagnosisOptions.filter(o=>o.good).map(o=>o.id);const correct=chosen.filter(id=>good.includes(id)).length;const bad=chosen.filter(id=>!good.includes(id)).length;state.diagnosisScore=Math.max(0,Math.round((correct/good.length)*20-bad*3));const missing=diagnosisOptions.filter(o=>o.good&&!chosen.includes(o.id)).map(o=>o.title);feedback(document.getElementById('diagnosisFeedback'),`<strong>${correct===5&&bad===0?'Diagnóstico preciso.':'Revisa el diagnóstico.'}</strong> Has identificado ${correct} de 5 necesidades relevantes${bad?` y has seleccionado ${bad} distractor(es).`:'.'}${missing.length?`<br><br>Faltaría considerar: ${missing.join(', ')}.`:''}<br><br><strong>Clave teórica:</strong> el Tema 1 no reduce el aprendizaje al rendimiento académico. También contempla adaptación, autonomía, interacción social y disposición para seguir aprendiendo a lo largo de la vida.<br><button class="primary" id="toTheory">Continuar</button>`,correct>=4&&bad===0?'good':'warn');document.getElementById('toTheory').addEventListener('click',()=>show('theory'));});

document.getElementById('evaluateTheory').addEventListener('click',()=>{let correct=0;theoryItems.forEach((item,i)=>{if(document.getElementById(`theory-${i}`).value===item.correct)correct++;});state.theoryScore=Math.round((correct/theoryItems.length)*20);feedback(document.getElementById('theoryFeedback'),`<strong>${correct===5?'Excelente conexión teoría-práctica.':'Hay relaciones que conviene revisar.'}</strong> Has identificado correctamente ${correct} de 5 relaciones.<br><br><strong>Mapa teórico del Tema 1:</strong> Piaget orienta la adecuación de actividades al desarrollo cognitivo; Vygotsky sitúa el aprendizaje en la interacción social y la zona de desarrollo próximo; Bandura explica el aprendizaje por observación y modelado; Erikson ayuda a interpretar los conflictos psicosociales de cada etapa; Bowlby recuerda la importancia de relaciones estables y un entorno seguro para el desarrollo y el aprendizaje.<br><button class="primary" id="toApply">Continuar</button>`,correct>=4?'good':'warn');document.getElementById('toApply').addEventListener('click',()=>show('apply'));});

document.getElementById('evaluateApply').addEventListener('click',()=>{let correct=0;const explanations=[];applyItems.forEach((item,i)=>{if(document.getElementById(`apply-${i}`).value===item.correct)correct++;explanations.push(`<li><strong>${item.prompt}</strong> ${item.why}</li>`);});state.applyScore=Math.round((correct/applyItems.length)*15);feedback(document.getElementById('applyFeedback'),`<strong>${correct===5?'Decisiones muy coherentes.':'Revisa algunas decisiones.'}</strong> Has resuelto correctamente ${correct} de 5 situaciones.<ul>${explanations.join('')}</ul><p>La idea central es que una teoría psicopedagógica adquiere valor educativo cuando se traduce en decisiones concretas sobre actividades, relaciones, apoyos y feedback.</p><button class="primary" id="toOpen">Continuar</button>`,correct>=4?'good':'warn');document.getElementById('toOpen').addEventListener('click',()=>show('open'));});

function includesAny(text,terms){return terms.some(t=>text.includes(t));}
function scoreGroup(text,groups,max){let score=0;groups.forEach(g=>{if(includesAny(text,g.terms))score+=g.points;});return Math.min(max,score);}

document.getElementById('evaluateOpen').addEventListener('click',()=>{const raw=document.getElementById('openAnswer').value.trim();const text=raw.toLowerCase();const notes=[];
const exploration=scoreGroup(text,[{terms:['curiosidad','exploración','exploracion','experiment','proyecto','reto','preguntas','investig'],points:8},{terms:['aprendizaje a lo largo de la vida','aprendizaje permanente','aprender a aprender','aprendizaje autónomo','aprendizaje autonomo','autonomía','autonomia','adaptabilidad'],points:7}],15);
const social=scoreGroup(text,[{terms:['habilidades sociales','trabajo en equipo','aprendizaje cooperativo','cooperación','cooperacion','juego de rol','juegos de rol','resolución de conflictos','resolucion de conflictos'],points:8},{terms:['bandura','modelado','observación','observacion','vygotsky','zona de desarrollo próximo','zona de desarrollo proximo','andamiaje'],points:7}],15);
const self=scoreGroup(text,[{terms:['autoconocimiento','autoestima','fortalezas','debilidades','intereses','pasiones'],points:8},{terms:['logros','competencia','confianza','reconocer el esfuerzo','reconocimiento','retroalimentación','retroalimentacion'],points:7}],15);
const erikson=scoreGroup(text,[{terms:['erikson'],points:5},{terms:['industria','inferioridad'],points:7},{terms:['competencia','sentirse competente','capacidad','tareas progresivas','desafíos alcanzables','desafios alcanzables'],points:8}],20);
const theories=scoreGroup(text,[{terms:['bandura','aprendizaje social','modelado'],points:4},{terms:['vygotsky','zona de desarrollo próximo','zona de desarrollo proximo','andamiaje'],points:4},{terms:['bowlby','apego','entorno seguro','ambiente seguro'],points:4},{terms:['piaget','desarrollo cognitivo','experimentación','experimentacion'],points:3}],15);
const context=scoreGroup(text,[{terms:['familia','familias','comunidad','proyecto comunitario','participación familiar','participacion familiar'],points:6},{terms:['formación docente','formacion docente','formación continua','formacion continua','capacitación','capacitacion'],points:5},{terms:['mentalidad de crecimiento','error','errores','persistencia','esfuerzo','desafíos como oportunidades','desafios como oportunidades'],points:5},{terms:['currículo','curriculo','práctica diaria','practica diaria','coherencia','integrar'],points:4}],20);
state.openBreakdown={exploration,social,self,erikson,theories,context};const rawOpen=Object.values(state.openBreakdown).reduce((a,b)=>a+b,0);state.openScore=Math.round((rawOpen/100)*45);
if(exploration<10)notes.push('Relaciona la curiosidad con el aprendizaje a lo largo de la vida: aprender a aprender, explorar, buscar información y adaptarse a contextos nuevos.');
if(social<10)notes.push('Profundiza en habilidades sociales conectándolas con Bandura —modelado y aprendizaje observacional— y/o Vygotsky —interacción social, ZDP y andamiaje—.');
if(self<10)notes.push('Concreta cómo trabajarías autoconocimiento, autoestima y percepción de competencia mediante experiencias y feedback.');
if(erikson<14)notes.push('No basta con nombrar a Erikson: explica la etapa industria frente a inferioridad y cómo las tareas pueden reforzar competencia en lugar de sentimientos de inferioridad.');
if(theories<9)notes.push('Integra otras teorías del Tema 1: Piaget, Vygotsky, Bandura y Bowlby, indicando una aplicación práctica de cada una que resulte pertinente.');
if(context<13)notes.push('Incluye familia/comunidad, mentalidad de crecimiento y formación continua del profesorado como parte de una intervención coherente y sostenida.');
if(raw.length<650)notes.push('Desarrolla más la respuesta: se espera justificar las medidas y no solo enumerarlas.');
const totalPreview=state.diagnosisScore+state.theoryScore+state.applyScore+state.openScore;
feedback(document.getElementById('openFeedback'),`<strong>Revisión formativa de la propuesta:</strong><div class="breakdown"><div>Exploración y aprendizaje permanente: ${exploration}/15</div><div>Habilidades sociales y cooperación: ${social}/15</div><div>Autoconocimiento y autoestima: ${self}/15</div><div>Erikson y desarrollo psicosocial: ${erikson}/20</div><div>Otras teorías: ${theories}/15</div><div>Familia, formación y coherencia: ${context}/20</div></div>${notes.length?'<ul>'+notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'La propuesta conecta de forma equilibrada el caso con las teorías psicopedagógicas y el aprendizaje a lo largo de la vida.'}<p class="muted">Puntuación provisional global: ${totalPreview}/100. Esta revisión es automática y orientativa; valora la presencia y conexión de conceptos, no sustituye la valoración docente del significado global de la respuesta.</p><button class="primary" id="toSurvey">Continuar al cuestionario final</button>`,rawOpen>=70?'good':'warn');document.getElementById('toSurvey').addEventListener('click',()=>show('survey'));});

document.getElementById('finishSurvey').addEventListener('click',()=>{const likert=[];let complete=true;surveyStatements.forEach((_,i)=>{const checked=document.querySelector(`input[name="survey-${i}"]:checked`);if(!checked)complete=false;likert.push(checked?Number(checked.value):null);});if(!complete){feedback(document.getElementById('surveyFeedback'),'<strong>Falta completar el cuestionario.</strong> Responde a todos los ítems antes de finalizar.','warn');return;}state.survey={session:'sesion-02',instrumentVersion:commonSurvey.version,likert,best:document.getElementById('surveyBest').value.trim(),improve:document.getElementById('surveyImprove').value.trim(),useful:document.getElementById('surveyUseful').value,timestamp:new Date().toISOString()};const total=state.diagnosisScore+state.theoryScore+state.applyScore+state.openScore;const record={session:'sesion-02',topic:'tema-01',score:total,components:{diagnosis:state.diagnosisScore,theory:state.theoryScore,application:state.applyScore,open:state.openScore},openBreakdown:state.openBreakdown,openAnswer:document.getElementById('openAnswer').value.trim(),survey:state.survey};localStorage.setItem('eaweb-sesion-02',JSON.stringify(record));document.getElementById('finalScore').textContent=total;document.getElementById('resultText').innerHTML=`<p><strong>Has completado la Sesión 2.</strong> El resultado combina diagnóstico, comprensión de las teorías, toma de decisiones y resolución abierta del caso.</p><div class="breakdown"><div>Diagnóstico: ${state.diagnosisScore}/20</div><div>Teoría en acción: ${state.theoryScore}/20</div><div>Aplicación: ${state.applyScore}/15</div><div>Resolución abierta: ${state.openScore}/45</div></div><p>La finalidad no es memorizar nombres de autores, sino aprender a justificar decisiones educativas mediante la teoría del Tema 1.</p>`;show('result');});

document.getElementById('restart').addEventListener('click',()=>location.reload());