const screens={case:'screen-case',diagnosis:'screen-diagnosis',theory:'screen-theory',apply:'screen-apply',open:'screen-open',survey:'screen-survey',result:'screen-result'};
const state={diagnosisScore:0,theoryScore:0,applyScore:0,openScore:0,openRubric:0,openBreakdown:{},survey:{}};

const diagnosisOptions=[
{id:'ethnic',title:'Divisiones por origen étnico',text:'El origen étnico está generando separación entre estudiantes.',good:true},
{id:'socio',title:'Divisiones socioeconómicas',text:'Las diferencias socioeconómicas también están afectando la convivencia.',good:true},
{id:'group',title:'Deterioro de la dinámica grupal',text:'Los docentes observan un impacto negativo en el funcionamiento del grupo.',good:true},
{id:'participation',title:'Menor participación conjunta',text:'Ha disminuido la participación en actividades compartidas.',good:true},
{id:'community',title:'Necesidad de respuesta comunitaria',text:'La dirección quiere implicar a toda la comunidad educativa.',good:true},
{id:'grades',title:'Fracaso académico generalizado',text:'El problema principal es una caída global de calificaciones.',good:false},
{id:'attendance',title:'Absentismo',text:'El caso describe faltas reiteradas de asistencia.',good:false},
{id:'devices',title:'Brecha tecnológica',text:'La falta de dispositivos es el origen principal del problema.',good:false}
];

const theoryItems=[
{prompt:'Estudiantes previamente formados ayudan a compañeros a resolver un desacuerdo.',correct:'peer',options:[['peer','Mediación por pares.'],['coop','Aprendizaje cooperativo.'],['ei','Inteligencia emocional.'],['rv','Realidad Virtual.']]},
{prompt:'El grupo trabaja con un objetivo común, roles definidos y responsabilidad individual y colectiva.',correct:'coop',options:[['coop','Aprendizaje cooperativo.'],['peer','Mediación por pares.'],['rv','Realidad Virtual.'],['punish','Sanción disciplinaria.']]},
{prompt:'El alumnado aprende a reconocer emociones, autorregularse y comprender las emociones de los demás.',correct:'ei',options:[['ei','Inteligencia emocional.'],['coop','Aprendizaje cooperativo.'],['peer','Mediación por pares.'],['rules','Normas únicamente.']]},
{prompt:'Se simula un conflicto en un entorno seguro y el alumnado ensaya respuestas con retroalimentación.',correct:'rv',options:[['rv','Realidad Virtual para aprendizaje experiencial.'],['peer','Mediación por pares.'],['coop','Aprendizaje cooperativo.'],['lecture','Explicación magistral.']]},
{prompt:'El docente adapta metodologías al contexto, promueve pensamiento crítico y revisa sus propios sesgos.',correct:'architect',options:[['architect','Maestro como arquitecto del aprendizaje.'],['neutral','Aplicación rígida de una única metodología.'],['delegate','Delegación total en las familias.'],['avoid','Evitar abordar el conflicto.']]}
];

const applyItems=[
{prompt:'Dos estudiantes tienen un desacuerdo cotidiano y ambos aceptan dialogar.',correct:'peer',options:[['peer','Activar mediación por pares con alumnado formado.'],['ignore','Ignorarlo.'],['expel','Aplicar expulsión automática.'],['separate','Separarlos permanentemente.']],why:'La mediación por pares favorece empatía y comunicación, aunque los casos graves requieren intervención adulta.'},
{prompt:'Hay poca relación entre estudiantes de diferentes orígenes.',correct:'coop',options:[['coop','Diseñar tareas cooperativas con grupos heterogéneos, roles y meta común.'],['same','Mantener los grupos habituales.'],['alone','Priorizar trabajo individual.'],['compete','Aumentar la competición entre grupos.']],why:'El aprendizaje cooperativo genera interdependencia positiva y obliga a trabajar con perspectivas diversas.'},
{prompt:'Un conflicto escala porque el alumnado no sabe manejar frustración y enfado.',correct:'ei',options:[['ei','Trabajar reconocimiento emocional, autorregulación, empatía y habilidades sociales.'],['rules','Añadir solo más normas.'],['ignore','No intervenir.'],['punish','Sancionar sin trabajar habilidades.']],why:'La inteligencia emocional permite gestionar emociones que influyen directamente en la resolución de conflictos.'},
{prompt:'El centro dispone de recursos tecnológicos y quiere practicar respuestas ante discriminación sin exponer a nadie a una situación real.',correct:'rv',options:[['rv','Usar RV como simulación complementaria y segura.'],['replace','Sustituir toda la intervención educativa por RV.'],['game','Usarla solo como entretenimiento.'],['none','Evitar cualquier tecnología.']],why:'La RV puede facilitar aprendizaje experiencial, empatía, comunicación y feedback inmediato, pero es un recurso complementario.'},
{prompt:'El docente detecta que aplica siempre las mismas estrategias aunque no funcionen con este grupo.',correct:'architect',options:[['architect','Revisar el contexto, adaptar metodologías y reflexionar sobre la propia práctica y posibles sesgos.'],['same','Mantener el mismo enfoque para todos.'],['family','Trasladar toda la responsabilidad a las familias.'],['wait','Esperar a que el clima mejore solo.']],why:'El maestro arquitecto selecciona metodologías de forma flexible, crítica y ajustada al contexto.'},
{prompt:'Para que la mejora no dependa de un solo docente...',correct:'collab',options:[['collab','Coordinar profesorado, familias y comunidad mediante redes o comités de trabajo y seguimiento.'],['solo','Dejar toda la intervención al tutor.'],['private','Evitar compartir estrategias.'],['temporary','Realizar una única actividad aislada.']],why:'La prevención de la discriminación se fortalece cuando existe colaboración entre escuela, familia y entorno.'}
];

const commonSurvey=window.COMMON_SURVEY;const surveyStatements=commonSurvey.statements;
function show(name){Object.values(screens).forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById(screens[name]).classList.add('active');const steps={case:1,diagnosis:2,theory:3,apply:4,open:5,survey:6,result:6};const step=steps[name];document.getElementById('progressLabel').textContent=name==='result'?'Actividad completada':`Paso ${step} de 6`;document.getElementById('progressBar').style.width=`${name==='result'?100:(step/6)*100}%`;window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.next)));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));function feedback(el,html,type='good'){el.className=`feedback ${type}`;el.innerHTML=html;}
function renderDiagnosis(){const grid=document.getElementById('diagnosisGrid');diagnosisOptions.forEach(o=>{const btn=document.createElement('button');btn.className='block-option';btn.dataset.id=o.id;btn.innerHTML=`<strong>${o.title}</strong><span>${o.text}</span>`;btn.addEventListener('click',()=>btn.classList.toggle('selected'));grid.appendChild(btn);});}
function renderTheory(){const grid=document.getElementById('theoryGrid');theoryItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="theory-${i}"><option value="">Selecciona la estrategia</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderApply(){const grid=document.getElementById('applyGrid');applyItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="apply-${i}"><option value="">Selecciona la actuación</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderSurvey(){const box=document.getElementById('surveyItems');surveyStatements.forEach((s,i)=>{const div=document.createElement('div');div.className='survey-item';div.innerHTML=`<p><strong>${i+1}.</strong> ${s}</p><div class="likert">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="survey-${i}" value="${n}"> ${n}</label>`).join('')}</div>`;box.appendChild(div);});document.getElementById('surveyUseful').innerHTML='<option value="">Selecciona una opción</option>'+commonSurvey.usefulOptions.map(o=>`<option>${o}</option>`).join('');}
renderDiagnosis();renderTheory();renderApply();renderSurvey();

document.getElementById('evaluateDiagnosis').addEventListener('click',()=>{const chosen=[...document.querySelectorAll('.block-option.selected')].map(x=>x.dataset.id);const good=diagnosisOptions.filter(o=>o.good).map(o=>o.id);const correct=chosen.filter(id=>good.includes(id)).length;const bad=chosen.filter(id=>!good.includes(id)).length;state.diagnosisScore=Math.max(0,Math.round((correct/good.length)*20-bad*3));feedback(document.getElementById('diagnosisFeedback'),`<strong>${correct===5&&bad===0?'Diagnóstico preciso.':'Revisa algunos elementos.'}</strong> Has identificado ${correct} de 5 señales relevantes${bad?` y ${bad} distractor(es).`:'.'}<br><br><strong>Clave:</strong> el problema combina divisiones por origen, pérdida de cooperación y menor participación; por eso la respuesta debe modificar las interacciones, no limitarse a sancionar.<br><button class="primary" id="toTheory">Continuar</button>`,correct>=4&&bad===0?'good':'warn');document.getElementById('toTheory').addEventListener('click',()=>show('theory'));});

document.getElementById('evaluateTheory').addEventListener('click',()=>{let correct=0;theoryItems.forEach((item,i)=>{if(document.getElementById(`theory-${i}`).value===item.correct)correct++;});state.theoryScore=Math.round((correct/theoryItems.length)*20);feedback(document.getElementById('theoryFeedback'),`<strong>${correct===5?'Conexión teórica completa.':'Hay relaciones que conviene revisar.'}</strong> Has resuelto ${correct} de 5 situaciones.<br><br><strong>Mapa del Tema 4:</strong> mediación por pares, aprendizaje cooperativo, inteligencia emocional y RV son estrategias diferentes pero complementarias; el docente debe seleccionar la adecuada según el conflicto y el contexto.<br><button class="primary" id="toApply">Continuar</button>`,correct>=4?'good':'warn');document.getElementById('toApply').addEventListener('click',()=>show('apply'));});

document.getElementById('evaluateApply').addEventListener('click',()=>{let correct=0;const explanations=[];applyItems.forEach((item,i)=>{if(document.getElementById(`apply-${i}`).value===item.correct)correct++;explanations.push(`<li>${item.why}</li>`);});state.applyScore=Math.round((correct/applyItems.length)*15);feedback(document.getElementById('applyFeedback'),`<strong>${correct===applyItems.length?'Selección estratégica excelente.':'Revisa algunas decisiones.'}</strong> Has resuelto ${correct} de ${applyItems.length} situaciones.<ul>${explanations.join('')}</ul><p>La clave es elegir estrategias distintas según la naturaleza del conflicto y combinarlas dentro de un diseño docente coherente.</p><button class="primary" id="toOpen">Continuar</button>`,correct>=5?'good':'warn');document.getElementById('toOpen').addEventListener('click',()=>show('open'));});

function has(text,terms){return terms.some(t=>text.includes(t));}function pointsFor(text,checks){return checks.reduce((s,c)=>s+(has(text,c.terms)?c.points:0),0);}
document.getElementById('evaluateOpen').addEventListener('click',()=>{const raw=document.getElementById('openAnswer').value.trim();const text=raw.toLowerCase();const notes=[];
const peer=Math.min(20,pointsFor(text,[{terms:['mediación por pares','mediacion por pares'],points:7},{terms:['alumnos mediadores','estudiantes mediadores','mediadores voluntarios','mediadores previamente capacitados','formar a alumnos mediadores'],points:5},{terms:['empatía','empatia','comunicación','comunicacion'],points:4},{terms:['intervención adulta','intervencion adulta','casos graves','supervisión adulta','supervision adulta'],points:4}]));
const coop=Math.min(20,pointsFor(text,[{terms:['aprendizaje cooperativo'],points:6},{terms:['interdependencia positiva'],points:5},{terms:['roles','responsabilidad individual','responsabilidad grupal','responsabilidad compartida'],points:5},{terms:['grupos heterogéneos','grupos heterogeneos','objetivo común','objetivo comun'],points:4}]));
const emotion=Math.min(15,pointsFor(text,[{terms:['inteligencia emocional'],points:5},{terms:['autoconocimiento'],points:3},{terms:['autorregulación','autorregulacion'],points:3},{terms:['empatía','empatia'],points:2},{terms:['habilidades sociales'],points:2}]));
const rv=Math.min(10,pointsFor(text,[{terms:['realidad virtual','rv'],points:4},{terms:['simulación','simulacion','entorno seguro'],points:3},{terms:['feedback inmediato','retroalimentación inmediata','retroalimentacion inmediata','aprendizaje experiencial'],points:3}]));
const architect=Math.min(20,pointsFor(text,[{terms:['arquitecto del aprendizaje'],points:5},{terms:['pensamiento crítico','pensamiento critico','participación democrática','participacion democratica','valoración de la diversidad','valoracion de la diversidad'],points:4},{terms:['adaptar','flexible','creativa','creativo','contexto','necesidades'],points:4},{terms:['prejuicios','estereotipos','sesgos'],points:4},{terms:['reflexión','reflexion','auto-observación','autoobservación','autoobservacion'],points:3}]));
const collab=Math.min(15,pointsFor(text,[{terms:['familias','familia'],points:4},{terms:['comunidad','comunidad educativa'],points:3},{terms:['profesorado','docentes'],points:3},{terms:['comité','comites','comités','redes de trabajo','trabajo colaborativo'],points:3},{terms:['seguimiento','evaluación','evaluacion','revisar','ajustar'],points:2}]));
const rubric=peer+coop+emotion+rv+architect+collab;state.openRubric=rubric;state.openScore=Math.round(rubric*.45);state.openBreakdown={peer,coop,emotion,rv,architect,collab};if(peer<15)notes.push('Desarrolla mejor la mediación por pares y sus límites.');if(coop<15)notes.push('Explica cómo organizarías el aprendizaje cooperativo.');if(emotion<10)notes.push('Incluye autoconocimiento, autorregulación y empatía.');if(architect<15)notes.push('Refuerza el papel del docente como arquitecto del aprendizaje y la revisión de sesgos.');if(collab<10)notes.push('Concreta la colaboración con familias/comunidad y el seguimiento.');const type=rubric>=80?'good':'warn';feedback(document.getElementById('openFeedback'),`<strong>Valoración: ${rubric}/100.</strong><div class="breakdown"><div>Mediación por pares: ${peer}/20</div><div>Aprendizaje cooperativo: ${coop}/20</div><div>Inteligencia emocional: ${emotion}/15</div><div>RV: ${rv}/10</div><div>Arquitecto del aprendizaje: ${architect}/20</div><div>Colaboración y seguimiento: ${collab}/15</div></div>${notes.length?`<p><strong>Para mejorar:</strong> ${notes.join(' ')}</p>`:'<p>Tu propuesta integra los componentes clave del Tema 4.</p>'}<button class="primary" id="toSurvey">Continuar</button>`,type);document.getElementById('toSurvey').addEventListener('click',()=>show('survey'));});

document.getElementById('finishSurvey').addEventListener('click',()=>{const vals=surveyStatements.map((_,i)=>document.querySelector(`input[name="survey-${i}"]:checked`)?.value||'');if(vals.some(v=>!v)){feedback(document.getElementById('surveyFeedback'),'Completa las 10 valoraciones antes de finalizar.','warn');return;}state.survey={likert:vals.map(Number),best:document.getElementById('surveyBest').value.trim(),improve:document.getElementById('surveyImprove').value.trim(),useful:document.getElementById('surveyUseful').value};const total=Math.min(100,state.diagnosisScore+state.theoryScore+state.applyScore+state.openScore);document.getElementById('finalScore').textContent=total;document.getElementById('resultText').innerHTML=`<p><strong>Desglose:</strong></p><div class="breakdown"><div>Diagnóstico: ${state.diagnosisScore}/20</div><div>Teoría: ${state.theoryScore}/20</div><div>Aplicación: ${state.applyScore}/15</div><div>Resolución abierta: ${state.openScore}/45</div></div><p>El objetivo es comprender que prevenir la discriminación exige diseñar interacciones cooperativas, enseñar a resolver conflictos y seleccionar estrategias ajustadas al contexto. La mediación, la cooperación, la inteligencia emocional y la tecnología funcionan mejor cuando forman parte de un diseño docente reflexivo e inclusivo.</p>`;localStorage.setItem('eaweb-sesion-08',JSON.stringify({session:'sesion-08',topic:'tema-04',timestamp:new Date().toISOString(),scores:{diagnosis:state.diagnosisScore,theory:state.theoryScore,apply:state.applyScore,open:state.openScore,total},openRubric:state.openRubric,openBreakdown:state.openBreakdown,openAnswer:document.getElementById('openAnswer').value,survey:state.survey}));show('result');});
document.getElementById('restart').addEventListener('click',()=>{localStorage.removeItem('eaweb-sesion-08');location.reload();});