const screens={case:'screen-case',diagnosis:'screen-diagnosis',theory:'screen-theory',apply:'screen-apply',open:'screen-open',survey:'screen-survey',result:'screen-result'};
const state={diagnosisScore:0,theoryScore:0,applyScore:0,openScore:0,openRubric:0,openBreakdown:{},survey:{}};

const diagnosisOptions=[
{id:'variable',title:'Implicación familiar desigual',text:'Las familias presentan niveles diferentes de participación en la vida escolar.',good:true},
{id:'impact',title:'Impacto en el rendimiento',text:'El caso relaciona esa variabilidad con el desempeño académico de algunos alumnos.',good:true},
{id:'alliance',title:'Necesidad de una alianza más fuerte',text:'El centro busca reforzar la colaboración entre hogar y escuela.',good:true},
{id:'participation',title:'Participación familiar como reto',text:'La escuela quiere implicar activamente a las familias en el proceso educativo.',good:true},
{id:'wellbeing',title:'Bienestar y educación compartida',text:'El centro reconoce que el bienestar y el aprendizaje no dependen solo del aula.',good:true},
{id:'bullying',title:'Acoso escolar generalizado',text:'El problema central es un aumento de casos de bullying entre iguales.',good:false},
{id:'digital',title:'Falta de dispositivos',text:'La causa principal es una brecha tecnológica en el alumnado.',good:false},
{id:'curriculum',title:'Currículo inadecuado',text:'El caso atribuye el problema a contenidos curriculares desactualizados.',good:false}
];

const theoryItems=[
{prompt:'La escuela informa periódicamente a las familias del progreso, actividades y dificultades.',correct:'communication',options:[['communication','Comunicación abierta, regular y bidireccional.'],['control','Control unilateral de las familias.'],['homework','Aprendizaje únicamente en el hogar.'],['distance','Separación de responsabilidades.']]},
{prompt:'Las familias participan en talleres, aula, excursiones y espacios de decisión.',correct:'participation',options:[['participation','Participación activa de las familias en la vida escolar.'],['passive','Recepción pasiva de información.'],['punitive','Supervisión disciplinaria.'],['individual','Responsabilidad exclusiva del alumno.']]},
{prompt:'La lectura compartida, las tareas acompañadas y las visitas culturales complementan lo trabajado en clase.',correct:'home',options:[['home','Colaboración en el aprendizaje en el hogar.'],['schoolonly','Aprendizaje exclusivamente escolar.'],['grading','Evaluación sumativa.'],['selection','Selección del alumnado.']]},
{prompt:'El centro adapta horarios, canales y formas de colaboración según las circunstancias de cada familia.',correct:'flexibility',options:[['flexibility','Participación flexible y ajustada a la realidad familiar.'],['same','Una única forma válida de implicación.'],['absence','Interpretar menor presencia como desinterés.'],['pressure','Exigir idéntico nivel de presencia física.']]},
{prompt:'Familia y escuela comparten metas, expectativas y apoyos, respetando sus funciones.',correct:'coresponsibility',options:[['coresponsibility','Corresponsabilidad educativa y respeto mutuo.'],['school','La escuela asume toda la responsabilidad.'],['family','La familia asume toda la responsabilidad.'],['separate','Cada agente trabaja sin coordinación.']]}
];

const applyItems=[
{prompt:'Una familia no puede acudir a reuniones por su horario laboral. ¿Qué actuación es más adecuada?',correct:'channels',options:[['channels','Ofrecer alternativas: tutoría online, teléfono, correo o distintos horarios.'],['blame','Interpretar la ausencia como falta de interés.'],['exclude','Excluirla de futuras decisiones.'],['student','Pedir al alumno que sustituya a la familia.']],why:'La alianza requiere comunicación accesible y flexible, no una única forma de participación.'},
{prompt:'El centro quiere que las familias pasen de recibir información a participar realmente.',correct:'workshops',options:[['workshops','Invitarlas a talleres, actividades de aula, excursiones y espacios de decisión.'],['newsletter','Enviar únicamente un boletín trimestral.'],['grades','Contactarlas solo cuando bajen las notas.'],['meeting','Limitar su papel a una reunión anual.']],why:'El Tema 5 propone programas de participación y asociaciones que den a las familias un papel activo.'},
{prompt:'Se quiere reforzar en casa lo trabajado en el aula sin sustituir la autonomía del niño.',correct:'homelearning',options:[['homelearning','Proponer lectura compartida, acompañamiento de tareas y experiencias culturales con orientación.'],['doit','Pedir a las familias que hagan las tareas por sus hijos.'],['extra','Aumentar tareas sin orientación.'],['none','Evitar cualquier relación entre hogar y aprendizaje.']],why:'El acompañamiento familiar debe reforzar el aprendizaje y favorecer autonomía y confianza.'},
{prompt:'Una familia dispone de pocos recursos y atraviesa una situación de estrés.',correct:'equity',options:[['equity','Adaptar apoyos y expectativas a su realidad, ofreciendo recursos y opciones viables de participación.'],['same','Exigir la misma disponibilidad y recursos que al resto.'],['label','Etiquetarla como poco implicada.'],['reduce','Bajar automáticamente las expectativas académicas del alumno.']],why:'Las circunstancias familiares pueden condicionar la participación; la respuesta debe ser comprensiva y equitativa.'},
{prompt:'¿Cómo deben plantearse las expectativas educativas compartidas?',correct:'realistic',options:[['realistic','Altas y realistas, acompañadas de refuerzo positivo y apoyos cuando sean necesarios.'],['low','Bajas para evitar frustraciones.'],['fixed','Idénticas sin considerar necesidades.'],['teacheronly','Definidas exclusivamente por el docente.']],why:'Las expectativas familiares influyen en la autoestima, metas y rendimiento, por lo que deben ser positivas y realistas.'},
{prompt:'¿Qué refleja mejor una alianza familia-escuela consolidada?',correct:'partnership',options:[['partnership','Comunicación, participación, apoyo en casa y planificación compartida con respeto a roles y responsabilidades.'],['info','La familia recibe información sin participar.'],['delegate','La escuela delega el aprendizaje en el hogar.'],['separate','Ambos trabajan en paralelo sin coordinación.']],why:'La colaboración efectiva implica corresponsabilidad, coordinación y respeto mutuo.'}
];

const commonSurvey=window.COMMON_SURVEY;
const surveyStatements=commonSurvey.statements;
function show(name){Object.values(screens).forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById(screens[name]).classList.add('active');const steps={case:1,diagnosis:2,theory:3,apply:4,open:5,survey:6,result:6};const step=steps[name];document.getElementById('progressLabel').textContent=name==='result'?'Actividad completada':`Paso ${step} de 6`;document.getElementById('progressBar').style.width=`${name==='result'?100:(step/6)*100}%`;window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.next)));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));
function feedback(el,html,type='good'){el.className=`feedback ${type}`;el.innerHTML=html;}
function renderDiagnosis(){const grid=document.getElementById('diagnosisGrid');diagnosisOptions.forEach(o=>{const btn=document.createElement('button');btn.className='block-option';btn.dataset.id=o.id;btn.innerHTML=`<strong>${o.title}</strong><span>${o.text}</span>`;btn.addEventListener('click',()=>btn.classList.toggle('selected'));grid.appendChild(btn);});}
function renderTheory(){const grid=document.getElementById('theoryGrid');theoryItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="theory-${i}"><option value="">Selecciona la explicación</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderApply(){const grid=document.getElementById('applyGrid');applyItems.forEach((item,i)=>{const card=document.createElement('div');card.className='match-card';card.innerHTML=`<strong>${item.prompt}</strong><select id="apply-${i}"><option value="">Selecciona la actuación</option>${item.options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;grid.appendChild(card);});}
function renderSurvey(){const box=document.getElementById('surveyItems');surveyStatements.forEach((s,i)=>{const div=document.createElement('div');div.className='survey-item';div.innerHTML=`<p><strong>${i+1}.</strong> ${s}</p><div class="likert">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="survey-${i}" value="${n}"> ${n}</label>`).join('')}</div>`;box.appendChild(div);});document.getElementById('surveyUseful').innerHTML='<option value="">Selecciona una opción</option>'+commonSurvey.usefulOptions.map(o=>`<option>${o}</option>`).join('');}
renderDiagnosis();renderTheory();renderApply();renderSurvey();

document.getElementById('evaluateDiagnosis').addEventListener('click',()=>{const chosen=[...document.querySelectorAll('.block-option.selected')].map(x=>x.dataset.id);const good=diagnosisOptions.filter(o=>o.good).map(o=>o.id);const correct=chosen.filter(id=>good.includes(id)).length;const bad=chosen.filter(id=>!good.includes(id)).length;state.diagnosisScore=Math.max(0,Math.round((correct/good.length)*20-bad*3));feedback(document.getElementById('diagnosisFeedback'),`<strong>${correct===5&&bad===0?'Diagnóstico preciso.':'Revisa algunos elementos.'}</strong> Has identificado ${correct} de 5 elementos relevantes${bad?` y ${bad} distractor(es).`:'.'}<br><br><strong>Clave del Tema 5:</strong> la participación familiar no es un elemento accesorio; familia y escuela son agentes educativos complementarios y su coordinación puede influir en el rendimiento y bienestar del alumnado.<br><button class="primary" id="toTheory">Continuar</button>`,correct>=4&&bad===0?'good':'warn');document.getElementById('toTheory').addEventListener('click',()=>show('theory'));});

document.getElementById('evaluateTheory').addEventListener('click',()=>{let correct=0;theoryItems.forEach((item,i)=>{if(document.getElementById(`theory-${i}`).value===item.correct)correct++;});state.theoryScore=Math.round((correct/theoryItems.length)*20);feedback(document.getElementById('theoryFeedback'),`<strong>${correct===5?'Conexión teórica completa.':'Hay relaciones que conviene revisar.'}</strong> Has resuelto ${correct} de 5 situaciones.<br><br><strong>Mapa del Tema 5:</strong> una alianza sólida combina comunicación regular, participación real, aprendizaje en el hogar, flexibilidad y corresponsabilidad educativa.<br><button class="primary" id="toApply">Continuar</button>`,correct>=4?'good':'warn');document.getElementById('toApply').addEventListener('click',()=>show('apply'));});

document.getElementById('evaluateApply').addEventListener('click',()=>{let correct=0;const explanations=[];applyItems.forEach((item,i)=>{if(document.getElementById(`apply-${i}`).value===item.correct)correct++;explanations.push(`<li>${item.why}</li>`);});state.applyScore=Math.round((correct/applyItems.length)*15);feedback(document.getElementById('applyFeedback'),`<strong>${correct===applyItems.length?'Decisiones muy coherentes.':'Revisa algunas decisiones.'}</strong> Has resuelto correctamente ${correct} de ${applyItems.length} situaciones.<ul>${explanations.join('')}</ul><p>La participación familiar efectiva no significa exigir la misma presencia a todas las familias, sino crear múltiples vías para que puedan implicarse de forma significativa.</p><button class="primary" id="toOpen">Continuar</button>`,correct>=5?'good':'warn');document.getElementById('toOpen').addEventListener('click',()=>show('open'));});

function has(text,terms){return terms.some(t=>text.includes(t));}
function pts(text,groups){return groups.reduce((s,g)=>s+(has(text,g.terms)?g.points:0),0);}
document.getElementById('evaluateOpen').addEventListener('click',()=>{const raw=document.getElementById('openAnswer').value.trim();const text=raw.toLowerCase();
const communication=Math.min(20,pts(text,[{terms:['comunicación abierta','comunicacion abierta','comunicación regular','comunicacion regular','comunicación bidireccional','comunicacion bidireccional'],points:8},{terms:['reuniones','correo','correos','boletines','plataformas digitales','tutoría online','tutoria online','teléfono','telefono'],points:6},{terms:['progreso','seguimiento','dificultades','necesidades'],points:6}]));
const participation=Math.min(20,pts(text,[{terms:['talleres','actividades de aula','excursiones','actividades escolares'],points:8},{terms:['toma de decisiones','espacios de decisión','espacios de decision','asociaciones de familias','ampas','ampa'],points:7},{terms:['participación activa','participacion activa','involucramiento','implicación familiar','implicacion familiar'],points:5}]));
const home=Math.min(15,pts(text,[{terms:['lectura compartida','lectura conjunta'],points:5},{terms:['tareas','deberes','acompañamiento de tareas','acompanamiento de tareas'],points:5},{terms:['experiencias culturales','museos','bibliotecas','aprendizaje en el hogar'],points:5}]));
const flexibility=Math.min(15,pts(text,[{terms:['flexible','flexibilidad','adaptar','adaptada','alternativas'],points:6},{terms:['circunstancias familiares','realidad familiar','recursos','tiempo','horarios'],points:5},{terms:['no interpretar','no asumir','no confundir','desinterés','desinteres','equidad'],points:4}]));
const expectations=Math.min(15,pts(text,[{terms:['expectativas positivas','expectativas altas','expectativas realistas','altas y realistas'],points:6},{terms:['refuerzo positivo','apoyo','apoyos'],points:5},{terms:['planificación','planificacion','seguimiento del alumnado','intervención','intervencion'],points:4}]));
const coresponsibility=Math.min(15,pts(text,[{terms:['respeto mutuo','roles y responsabilidades','responsabilidades complementarias'],points:5},{terms:['corresponsabilidad','colaboración','colaboracion','coordinación','coordinacion'],points:5},{terms:['agentes activos','participante activa','participantes activos','no solo receptoras','receptoras de información','receptoras de informacion'],points:5}]));
const rubric=communication+participation+home+flexibility+expectations+coresponsibility;state.openRubric=rubric;state.openScore=Math.round(rubric*.45);state.openBreakdown={communication,participation,home,flexibility,expectations,coresponsibility};
const type=rubric>=80?'good':'warn';feedback(document.getElementById('openFeedback'),`<strong>Valoración de la respuesta: ${rubric}/100.</strong><div class="breakdown"><div>Comunicación: ${communication}/20</div><div>Participación: ${participation}/20</div><div>Aprendizaje en el hogar: ${home}/15</div><div>Flexibilidad y equidad: ${flexibility}/15</div><div>Expectativas y apoyo: ${expectations}/15</div><div>Corresponsabilidad: ${coresponsibility}/15</div></div><p>${rubric===100?'La respuesta integra todos los componentes esenciales de la alianza familia-escuela previstos en el Tema 5.':'Revisa los apartados con menor puntuación e incorpora medidas concretas y justificadas.'}</p><button class="primary" id="toSurvey">Continuar</button>`,type);document.getElementById('toSurvey').addEventListener('click',()=>show('survey'));});

document.getElementById('finishSurvey').addEventListener('click',()=>{const responses=surveyStatements.map((_,i)=>document.querySelector(`input[name="survey-${i}"]:checked`)?.value||'');if(responses.some(v=>!v)){feedback(document.getElementById('surveyFeedback'),'<strong>Completa las 10 valoraciones antes de finalizar.</strong>','warn');return;}state.survey={responses,best:document.getElementById('surveyBest').value.trim(),improve:document.getElementById('surveyImprove').value.trim(),useful:document.getElementById('surveyUseful').value};const total=Math.min(100,state.diagnosisScore+state.theoryScore+state.applyScore+state.openScore);document.getElementById('finalScore').textContent=total;document.getElementById('resultText').innerHTML=`<p><strong>Puntuación global: ${total}/100.</strong></p><div class="breakdown"><div>Diagnóstico: ${state.diagnosisScore}/20</div><div>Teoría: ${state.theoryScore}/20</div><div>Aplicación: ${state.applyScore}/15</div><div>Resolución: ${state.openScore}/45</div></div><p>La actividad diferencia entre el rendimiento demostrado en las tareas y tu valoración personal del aprendizaje en el cuestionario final.</p>`;localStorage.setItem('eaweb-sesion-09',JSON.stringify({session:'sesion-09',topic:'tema-05',score:total,state,completedAt:new Date().toISOString()}));show('result');});

document.getElementById('restart').addEventListener('click',()=>{localStorage.removeItem('eaweb-sesion-09');location.reload();});